// src/sections.ts
// Pure string→string functions for Brief and Next Actions section manipulation.

import { ALL_CONTRACTS, SUBTYPE_SECTIONS } from './contracts.js'

const UNCHECKED_RE = /^- \[ \] (.+)$/gm

/**
 * Known structural section headings in Hafez entities and knowledge notes.
 * Derived from contracts.ts (defaultSections + optionalSections) plus
 * auto-generated sections not tracked in contracts (Related, Summary).
 * Only these are treated as section boundaries. Any other `## ` heading
 * inside section content (e.g. in a brief or session log) is preserved as-is.
 */
export const STRUCTURAL_SECTIONS = new Set([
  ...ALL_CONTRACTS.flatMap(c => [...c.defaultSections, ...c.optionalSections]),
  ...Object.values(SUBTYPE_SECTIONS).flat(),
  'Related',  // auto-generated by syncRelatedSection
  'Summary',  // used in session files
])

/**
 * Find the next structural `## Heading` boundary after a given position.
 * Skips `## ` headings that are not known structural sections (content headings).
 * Returns the index of the `\n` before the `## `, or -1 if no structural heading found.
 */
export function findNextStructuralHeading(body: string, from: number): number {
  const re = /\n## ([^\n]+)/g
  re.lastIndex = from
  let match
  while ((match = re.exec(body)) !== null) {
    const headingName = match[1].trim()
    if (STRUCTURAL_SECTIONS.has(headingName)) {
      return match.index
    }
  }
  return -1
}

// --- Internal helpers ---

/**
 * Find a ## Heading section and its content.
 * Returns { start, end, content } or null if not found.
 * Matches heading exactly (e.g. "## Brief" won't match "## Briefing").
 * Only treats known structural headings as section boundaries -- content
 * inside a section may contain arbitrary `## ` headings without corruption.
 */
export function findSection(body: string, heading: string): { start: number; end: number; content: string } | null {
  const re = new RegExp(`(^|\\n)(## ${escapeRegex(heading)})(?:\\n|$)`)
  const match = re.exec(body)
  if (!match) return null

  const start = match.index + match[1].length
  const afterHeading = start + match[2].length + 1

  // Find the next structural ## heading or EOF
  const nextHeading = findNextStructuralHeading(body, afterHeading)
  const end = nextHeading === -1 ? body.length : nextHeading

  const rawContent = body.slice(afterHeading, end)
  const content = rawContent.replace(/^\n+/, '').replace(/\n+$/, '')

  return { start, end, content }
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/**
 * Remove a section (heading + content) from body, cleaning up extra whitespace.
 */
function removeSection(body: string, heading: string): string {
  const section = findSection(body, heading)
  if (!section) return body

  const before = body.slice(0, section.start)
  const after = body.slice(section.end)

  // Clean up: avoid triple+ newlines at the splice point
  const trimmedBefore = before.replace(/\n+$/, '')
  const trimmedAfter = after.replace(/^\n+/, '')

  if (!trimmedBefore) return trimmedAfter
  if (!trimmedAfter) return trimmedBefore
  return trimmedBefore + '\n\n' + trimmedAfter
}

/**
 * Insert a new section before a target heading, or at EOF.
 * `before` is an array of headings to try inserting before (first found wins).
 */
function insertSectionBefore(body: string, heading: string, content: string, before: string[]): string {
  const sectionBlock = `## ${heading}\n\n${content}`

  for (const target of before) {
    const targetSection = findSection(body, target)
    if (targetSection) {
      const insertPoint = targetSection.start
      const textBefore = body.slice(0, insertPoint).replace(/\n+$/, '')
      const textAfter = body.slice(insertPoint)

      if (!textBefore) return sectionBlock + '\n\n' + textAfter
      return textBefore + '\n\n' + sectionBlock + '\n\n' + textAfter
    }
  }

  // No target found — append at EOF
  const trimmed = body.replace(/\n+$/, '')
  return trimmed + '\n\n' + sectionBlock
}

/**
 * Insert a new section after a target heading (and its content), or fall back to inserting before fallbacks.
 */
function insertSectionAfter(body: string, heading: string, content: string, after: string, beforeFallbacks: string[]): string {
  const afterSection = findSection(body, after)
  if (afterSection) {
    const insertPoint = afterSection.end
    const textBefore = body.slice(0, insertPoint).replace(/\n+$/, '')
    const textAfter = body.slice(insertPoint).replace(/^\n+/, '')
    const sectionBlock = `## ${heading}\n\n${content}`

    if (!textAfter) return textBefore + '\n\n' + sectionBlock
    return textBefore + '\n\n' + sectionBlock + '\n\n' + textAfter
  }

  // After-target not found — fall back to insertBefore logic
  return insertSectionBefore(body, heading, content, beforeFallbacks)
}

/**
 * Normalize text for matching: trim whitespace, replace smart quotes with
 * straight equivalents, normalize em-dashes to regular dashes.
 * Applied to both query and action text before comparison only — stored text is unchanged.
 */
function normalizeForMatch(s: string): string {
  return s
    .trim()
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/\u2014/g, '-')
}

/**
 * Match an action by case-insensitive substring against unchecked items.
 * Throws on 0 or >1 matches.
 */
function matchAction(body: string, query: string): string {
  const section = findSection(body, 'Next Actions')
  if (!section) throw new Error(`No matching action for "${query}"`)

  const normalizedQuery = normalizeForMatch(query).toLowerCase()
  const matches: string[] = []
  const allActions: string[] = []

  let m: RegExpExecArray | null
  const re = new RegExp(UNCHECKED_RE.source, 'gm')
  while ((m = re.exec(section.content)) !== null) {
    allActions.push(m[1])
    if (normalizeForMatch(m[1]).toLowerCase().includes(normalizedQuery)) {
      matches.push(m[1])
    }
  }

  if (matches.length === 0) {
    throw new Error(`No matching action for "${query}". Actions: ${JSON.stringify(allActions)}`)
  }
  if (matches.length > 1) throw new Error(`Ambiguous match for "${query}": ${matches.join(', ')}`)
  return matches[0]
}

// --- Brief functions ---

export function getBrief(body: string): string | null {
  const section = findSection(body, 'Brief')
  if (!section) return null
  return section.content || null
}

export function setBrief(body: string, content: string): string {
  const existing = findSection(body, 'Brief')
  if (existing) {
    // Replace existing brief content
    const updated = removeSection(body, 'Brief')
    return setBrief(updated, content)
  }

  // Insert before: Next Actions > Current State > Session Log > EOF
  return insertSectionBefore(body, 'Brief', content, ['Next Actions', 'Current State', 'Session Log'])
}

export function removeBrief(body: string): string {
  return removeSection(body, 'Brief')
}

// --- Next Actions functions ---

export function getNextActions(body: string): string[] {
  const section = findSection(body, 'Next Actions')
  if (!section) return []

  const actions: string[] = []
  let m: RegExpExecArray | null
  const re = new RegExp(UNCHECKED_RE.source, 'gm')
  while ((m = re.exec(section.content)) !== null) {
    actions.push(m[1])
  }
  return actions
}

export function addNextAction(body: string, action: string): string {
  const section = findSection(body, 'Next Actions')
  if (section) {
    // Add the new item at the end of unchecked items (before any checked items)
    const lines = section.content.split('\n')
    const lastUncheckedIdx = lines.reduce((last, line, i) => line.startsWith('- [ ] ') ? i : last, -1)
    const insertIdx = lastUncheckedIdx === -1 ? 0 : lastUncheckedIdx + 1
    lines.splice(insertIdx, 0, `- [ ] ${action}`)

    const newContent = lines.join('\n')
    const before = body.slice(0, section.start).replace(/\n+$/, '')
    const after = body.slice(section.end).replace(/^\n+/, '')

    const sectionBlock = `## Next Actions\n\n${newContent}`
    const parts = [before, sectionBlock, after].filter(Boolean)
    return parts.join('\n\n')
  }

  // No section — insert after Brief if present, otherwise before Session Log
  return insertSectionAfter(body, 'Next Actions', `- [ ] ${action}`, 'Brief', ['Session Log'])
}

export function completeNextAction(body: string, query: string): { matched: string; body: string } {
  const matched = matchAction(body, query)

  // Replace the unchecked item with checked
  const updatedBody = body.replace(`- [ ] ${matched}`, `- [x] ${matched}`)

  // Check if any unchecked items remain
  const remaining = getNextActions(updatedBody)
  if (remaining.length === 0) {
    return { matched, body: clearNextActions(updatedBody) }
  }

  return { matched, body: updatedBody }
}

export function removeNextAction(body: string, query: string): { matched: string; body: string } {
  const matched = matchAction(body, query)

  // Remove the line
  const line = `- [ ] ${matched}`
  const updatedBody = body.split('\n').filter(l => l !== line).join('\n')

  // Check if any unchecked items remain
  const remaining = getNextActions(updatedBody)
  if (remaining.length === 0) {
    return { matched, body: clearNextActions(updatedBody) }
  }

  return { matched, body: updatedBody }
}

export function clearNextActions(body: string): string {
  return removeSection(body, 'Next Actions')
}

// --- Summary derivation ---

export function firstNonEmptyLine(s: string | null | undefined): string {
  return s?.split('\n').find(l => l.trim())?.trim() ?? ''
}

/**
 * One-line summary for a doc: frontmatter description first, then the first
 * non-empty line of the kind's primary section (entity: Brief; knowledge:
 * Synthesis, falling back to Goal for plans; session: Summary).
 * Shared by the vault index and the OKF export so the two surfaces agree.
 */
export function deriveSummary(kind: 'entity' | 'knowledge' | 'session', fm: Record<string, any>, body: string): string {
  if (fm.description) return fm.description
  if (kind === 'entity') return firstNonEmptyLine(getBrief(body))
  if (kind === 'knowledge') {
    const synthesis = findSection(body, 'Synthesis')
    if (synthesis?.content) return firstNonEmptyLine(synthesis.content)
    return firstNonEmptyLine(findSection(body, 'Goal')?.content)
  }
  return firstNonEmptyLine(findSection(body, 'Summary')?.content)
}

// --- Related section functions ---

/** Matches [[slug]] or [[slug|display text]], capturing slug in group 1. Non-global — wrap with `new RegExp(WIKI_LINK_RE.source, 'g')` for iteration. */
export const WIKI_LINK_RE = /\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/

export function syncRelatedSection(
  body: string,
  frontmatter: { parent?: string; related?: string[] }
): string {
  const targets: Array<{ slug: string; label?: string }> = []
  if (frontmatter.parent) targets.push({ slug: frontmatter.parent, label: 'parent' })
  for (const slug of frontmatter.related ?? []) targets.push({ slug })

  if (targets.length === 0) {
    // No frontmatter links — remove Related section if present
    const existing = findSection(body, 'Related')
    if (!existing) return body
    const before = body.slice(0, existing.start).replace(/\n+$/, '')
    const after = body.slice(existing.end).replace(/^\n+/, '')
    return [before, after].filter(Boolean).join('\n\n')
  }

  // Strip existing Related section before checking coverage
  let authoredBody = body
  const existingRelated = findSection(body, 'Related')
  if (existingRelated) {
    const before = body.slice(0, existingRelated.start)
    const after = body.slice(existingRelated.end)
    authoredBody = (before + after).replace(/\n{3,}/g, '\n\n')
  }

  // Find which targets are NOT mentioned in authored body
  const mentionedSlugs = new Set<string>()
  let match: RegExpExecArray | null
  const re = new RegExp(WIKI_LINK_RE.source, 'g')
  while ((match = re.exec(authoredBody)) !== null) {
    mentionedSlugs.add(match[1])
  }

  const uncovered = targets.filter(t => !mentionedSlugs.has(t.slug))
  if (uncovered.length === 0) {
    // All covered inline — return body without Related section
    return authoredBody.replace(/\n+$/, '')
  }

  // Build Related section
  const lines = uncovered.map(t =>
    t.label ? `- [[${t.slug}]] (${t.label})` : `- [[${t.slug}]]`
  )
  const section = `## Related\n\n${lines.join('\n')}`

  // Append at end
  return authoredBody.replace(/\n+$/, '') + '\n\n' + section
}
